#!/bin/bash

set -e
export ES_VERSION=1.2.1
echo "Starting install"
adduser --disabled-login --gecos 'Elasticsearch' elasticsearch

sudo -u elasticsearch mkdir -p /home/elasticsearch/
sudo -u elasticsearch mkdir -p /home/elasticsearch/elasticsearch

sudo -u elasticsearch mkdir -p /home/elasticsearch/esdata/data
sudo -u elasticsearch mkdir -p /home/elasticsearch/esdata/plugins
sudo -u elasticsearch mkdir -p /home/elasticsearch/esdata/config

sudo -u elasticsearch cp /elasticsearch/setup/config/elasticsearch.yml /home/elasticsearch/esdata/config/
sudo -u elasticsearch cp /elasticsearch/setup/config/logging.yml /home/elasticsearch/esdata/config/

cd /home/elasticsearch/

sudo -u elasticsearch curl -o elasticsearch-$ES_VERSION.tar.gz https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.tar.gz
echo "Download completed"


sudo -u elasticsearch tar -xvvzf elasticsearch-$ES_VERSION.tar.gz --strip=1 -C /home/elasticsearch/elasticsearch

#install the marvel plugin
sudo -u elasticsearch curl -o /home/elasticsearch/esdata/plugins/marvel-latest.zip https://download.elasticsearch.org/elasticsearch/marvel/marvel-latest.zip
sudo -u elasticsearch unzip -d /home/elasticsearch/esdata/plugins/marvel /home/elasticsearch/esdata/plugins/marvel-latest.zip
sudo -u elasticsearch rm /home/elasticsearch/esdata/plugins/marvel-latest.zip

# create the /var/run/sshd directory (required for sshd to start)
mkdir -p /var/run/sshd

# configure supervisord to start openssh server
cat > /etc/supervisor/conf.d/openssh-server.conf <<EOF
[program:openssh-server]
priority=20
directory=/tmp
command=/usr/sbin/sshd -D
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF

# configure supervisord to start cron
cat > /etc/supervisor/conf.d/cron.conf <<EOF
[program:cron]
priority=20
directory=/tmp
command=/usr/sbin/cron -f
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF

