#!/bin/bash

set -e

echo "Starting install"
adduser --disabled-login --gecos 'Elasticsearch' elasticsearch

sudo -u elasticsearch -H mkdir -p /home/elasticsearch/
sudo -u elasticsearch -H mkdir -p /home/elasticsearch/elasticsearch

sudo -u elasticsearch -H mkdir -p /home/elasticsearch/esdata/data
sudo -u elasticsearch -H mkdir -p /home/elasticsearch/esdata/plugins
sudo -u elasticsearch -H mkdir -p /home/elasticsearch/esdata/config

sudo -u elasticsearch -H cp /elasticsearch/setup/config/elasticsearch.yml /home/elasticsearch/esdata/config/
cd /home/elasticsearch/

sudo -u elasticsearch -H curl -o elasticsearch-0.90.11.tar.gz https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.11.tar.gz
echo "Download completed"


sudo -u elasticsearch -H tar -xvvzf elasticsearch-0.90.11.tar.gz --strip=1 -C /home/elasticsearch/elasticsearch



# configure supervisord to start openssh server
cat > /etc/supervisor/conf.d/openssh-server.conf <<EOF
[program:openssh-server]
priority=20
directory=/tmp
command=/usr/sbin/sshd -D
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF
